version: '3'
services:
#    oori:
#      image: biotope/oori
#      environment:
#        - SERVER_PORT=9090
#        - CB_PORT=9090
#        - ENDPOINT_URL=http://fuseki:3030/odfData
#        - CB_HOSTNAME=biotope.iais.fraunhofer.de
#      ports:
#        - "9090:9090"
#        - "5005:5005"   # java debugging

#    fuseki:
#      build: fuseki/
#      ports:
#        - "3030:3030"

    web:
      image: firstimage
      ports:
       - "4000:80"

    nodejs:
      image: nodeimage
      ports:
       - "5080:5080"
       - "8090:8090"
      volumes:
       - "./modules:/src/app/storage"

    o-mi-node:
      image: o-mi-node
      ports:
       - "8080:8080"

#    dashboard-context-manager:
#      image: biotope/dashboard-context-manager
#      environment:
#        - SERVER_PORT=4040
#      ports:
#        - "4040:4040"

#    mongodata:
#      image: mongo
#      volumes:
#        - /data/db
#      command: --break-mongo

    mongodb:
#      build: mongodb/
      ports:
        - "27017:27017"
      image: mongo
      volumes:
        - './data/db:/data/db'

#      volumes_from: 
#        - mongodata
#      command: -smallfiles --rest --auth

#    data-science:
#      image: jupyter/datascience-notebook
#      ports:
#        - "8888:8888"

    node-red:
      image: node-red
      ports:
        - "1880:1880"
      volumes:
        - "./modules:/usr/src/node-red/modules"
      links:
        - mongodb
        - o-mi-node
#        - data-science


#    freeboard:


